<?xml version="1.0"?>
  <!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED>

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName, Res, DVer?, TSet?, TInst?, RunType?, DT?, Step*, Action+, DIter*, Action*, Summary?, NodeArgs?)> 
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,NodeArgs) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
> <Report ver="2.0" tmZone="北亚标准时间">
<General productName="Vugen" productVer="11" os="" host="MS-20180413TOZN"><DocLocation><![CDATA[D:\性能测试\day2\参数化组合]]></DocLocation></General>
<Doc rID="T1"   productName= "Vugen"  >
<DName><![CDATA[参数化组合]]></DName>
<Res><![CDATA[result1]]></Res>
<Action rID="T2">
<AName><![CDATA[vuser_init]]></AName>
<Summary sTime="2019/5/24 星期五 - 16:25:46" eTime="2019/5/24 星期五 - 16:25:46" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="5" >
<Disp><![CDATA[vuser_init Summary]]></Disp>
</NodeArgs>
</Action>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action]]></AName>
<Summary sTime="2019/5/24 星期五 - 16:25:46" eTime="2019/5/24 星期五 - 16:25:46" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="8" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T5">
<AName><![CDATA[Action2]]></AName>
<Summary sTime="2019/5/24 星期五 - 16:25:46" eTime="2019/5/24 星期五 - 16:25:46" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="10" >
<Disp><![CDATA[Action2 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="7" >
<Disp><![CDATA[参数化组合 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T6" iterID="2" >
<Action rID="T7">
<AName><![CDATA[Action]]></AName>
<Summary sTime="2019/5/24 星期五 - 16:25:46" eTime="2019/5/24 星期五 - 16:25:46" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="14" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T8">
<AName><![CDATA[Action2]]></AName>
<Summary sTime="2019/5/24 星期五 - 16:25:46" eTime="2019/5/24 星期五 - 16:25:46" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="16" >
<Disp><![CDATA[Action2 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="13" >
<Disp><![CDATA[参数化组合 Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T9" iterID="3" >
<Action rID="T10">
<AName><![CDATA[Action]]></AName>
<Summary sTime="2019/5/24 星期五 - 16:25:46" eTime="2019/5/24 星期五 - 16:25:46" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="20" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T11">
<AName><![CDATA[Action2]]></AName>
<Summary sTime="2019/5/24 星期五 - 16:25:46" eTime="2019/5/24 星期五 - 16:25:46" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="22" >
<Disp><![CDATA[Action2 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="19" >
<Disp><![CDATA[参数化组合 Iteration 3 (Row 3)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T12" iterID="4" >
<Action rID="T13">
<AName><![CDATA[Action]]></AName>
<Summary sTime="2019/5/24 星期五 - 16:25:46" eTime="2019/5/24 星期五 - 16:25:46" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="26" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T14">
<AName><![CDATA[Action2]]></AName>
<Summary sTime="2019/5/24 星期五 - 16:25:46" eTime="2019/5/24 星期五 - 16:25:46" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="28" >
<Disp><![CDATA[Action2 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="25" >
<Disp><![CDATA[参数化组合 Iteration 4 (Row 4)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T15" iterID="5" >
<Action rID="T16">
<AName><![CDATA[Action]]></AName>
<Summary sTime="2019/5/24 星期五 - 16:25:46" eTime="2019/5/24 星期五 - 16:25:46" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="32" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T17">
<AName><![CDATA[Action2]]></AName>
<Summary sTime="2019/5/24 星期五 - 16:25:46" eTime="2019/5/24 星期五 - 16:25:46" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="34" >
<Disp><![CDATA[Action2 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="31" >
<Disp><![CDATA[参数化组合 Iteration 5 (Row 5)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T18" iterID="6" >
<Action rID="T19">
<AName><![CDATA[Action]]></AName>
<Summary sTime="2019/5/24 星期五 - 16:25:46" eTime="2019/5/24 星期五 - 16:25:46" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="38" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T20">
<AName><![CDATA[Action2]]></AName>
<Summary sTime="2019/5/24 星期五 - 16:25:46" eTime="2019/5/24 星期五 - 16:25:46" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="40" >
<Disp><![CDATA[Action2 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="37" >
<Disp><![CDATA[参数化组合 Iteration 6 (Row 6)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T21" iterID="7" >
<Action rID="T22">
<AName><![CDATA[Action]]></AName>
<Summary sTime="2019/5/24 星期五 - 16:25:46" eTime="2019/5/24 星期五 - 16:25:46" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="44" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T23">
<AName><![CDATA[Action2]]></AName>
<Summary sTime="2019/5/24 星期五 - 16:25:46" eTime="2019/5/24 星期五 - 16:25:47" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="46" >
<Disp><![CDATA[Action2 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="43" >
<Disp><![CDATA[参数化组合 Iteration 7 (Row 7)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T24" iterID="8" >
<Action rID="T25">
<AName><![CDATA[Action]]></AName>
<Summary sTime="2019/5/24 星期五 - 16:25:47" eTime="2019/5/24 星期五 - 16:25:47" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="50" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T26">
<AName><![CDATA[Action2]]></AName>
<Summary sTime="2019/5/24 星期五 - 16:25:47" eTime="2019/5/24 星期五 - 16:25:47" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="52" >
<Disp><![CDATA[Action2 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="49" >
<Disp><![CDATA[参数化组合 Iteration 8 (Row 8)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T27" iterID="9" >
<Action rID="T28">
<AName><![CDATA[Action]]></AName>
<Summary sTime="2019/5/24 星期五 - 16:25:47" eTime="2019/5/24 星期五 - 16:25:47" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="56" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T29">
<AName><![CDATA[Action2]]></AName>
<Summary sTime="2019/5/24 星期五 - 16:25:47" eTime="2019/5/24 星期五 - 16:25:47" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="58" >
<Disp><![CDATA[Action2 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="55" >
<Disp><![CDATA[参数化组合 Iteration 9 (Row 9)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T30" iterID="10" >
<Action rID="T31">
<AName><![CDATA[Action]]></AName>
<Summary sTime="2019/5/24 星期五 - 16:25:47" eTime="2019/5/24 星期五 - 16:25:47" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="62" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T32">
<AName><![CDATA[Action2]]></AName>
<Summary sTime="2019/5/24 星期五 - 16:25:47" eTime="2019/5/24 星期五 - 16:25:47" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="64" >
<Disp><![CDATA[Action2 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="61" >
<Disp><![CDATA[参数化组合 Iteration 10 (Row 10)]]></Disp>
</NodeArgs>
</DIter>
<Action rID="T33">
<AName><![CDATA[vuser_end]]></AName>
<Summary sTime="2019/5/24 星期五 - 16:25:47" eTime="2019/5/24 星期五 - 16:25:47" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="67" >
<Disp><![CDATA[vuser_end Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="2019/5/24 星期五 - 16:25:46" eTime="2019/5/24 星期五 - 16:25:47" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="4" >
<Disp><![CDATA[Test 参数化组合 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>